const DAYS_IN_MS = 24 * 60 * 60 * 1000;

export const SESSION_DURATION_DAYS = 30;
export const SESSION_RENEWAL_THRESHOLD_DAYS = 7;

export const SESSION_DURATION_MS = SESSION_DURATION_DAYS * DAYS_IN_MS;
export const SESSION_RENEWAL_THRESHOLD_MS = SESSION_RENEWAL_THRESHOLD_DAYS * DAYS_IN_MS;
